import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';
import type { AnalyzeResponse, DomainStat } from '../types';

const THEME = {
  primary: [8, 145, 178] as [number, number, number],
  primaryBright: [34, 211, 238] as [number, number, number],
  dark: [11, 15, 20] as [number, number, number],
  panel: [15, 21, 28] as [number, number, number],
  headerText: [255, 255, 255] as [number, number, number],
  headerSub: [203, 213, 225] as [number, number, number],
  body: [15, 23, 42] as [number, number, number],
  label: [51, 65, 85] as [number, number, number],
  footer: [71, 85, 105] as [number, number, number],
};

const PAGE_W = 210;
const PAGE_H = 297;
const MARGIN = 18;
const CONTENT_W = PAGE_W - MARGIN * 2;

function formatBytes(bytes: number): string {
  if (bytes === 0) return '0 B';
  const units = ['B', 'KB', 'MB', 'GB'];
  const i = Math.floor(Math.log(bytes) / Math.log(1024));
  return `${(bytes / Math.pow(1024, i)).toFixed(2)} ${units[i]}`;
}

function formatList(items: string[]): string {
  return items.length > 0 ? items.join(', ') : 'None';
}

function domainName(entry: DomainStat | Record<string, unknown>): string {
  return String(
    'domain' in entry
      ? entry.domain
      : (entry as Record<string, unknown>).name ??
          (entry as Record<string, unknown>).host ??
          '—'
  );
}

function domainApp(entry: DomainStat | Record<string, unknown>): string {
  if ('application' in entry && entry.application) return String(entry.application);
  const rec = entry as Record<string, unknown>;
  return String(rec.app ?? rec.detectedApplication ?? '—');
}

function addFooter(doc: jsPDF, page: number, total: number) {
  const y = PAGE_H - 12;
  doc.setDrawColor(...THEME.primary);
  doc.setLineWidth(0.3);
  doc.line(MARGIN, y - 4, PAGE_W - MARGIN, y - 4);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(8);
  doc.setTextColor(...THEME.footer);
  doc.text('DPI Engine Report', MARGIN, y);
  doc.text('Generated by DPI Dashboard', PAGE_W / 2, y, { align: 'center' });
  doc.text(`Page ${page} of ${total}`, PAGE_W - MARGIN, y, { align: 'right' });
}

function addSectionTitle(doc: jsPDF, title: string, y: number): number {
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(12);
  doc.setTextColor(...THEME.primary);
  doc.text(title, MARGIN, y);
  doc.setDrawColor(...THEME.primary);
  doc.setLineWidth(0.4);
  doc.line(MARGIN, y + 2, MARGIN + 40, y + 2);
  return y + 10;
}

function drawTable(
  doc: jsPDF,
  startY: number,
  headers: string[],
  rows: string[][],
  colWidths: number[]
): number {
  const rowH = 8;
  let y = startY;

  doc.setFillColor(...THEME.panel);
  doc.rect(MARGIN, y - 5, CONTENT_W, rowH, 'F');
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(9);
  doc.setTextColor(...THEME.primaryBright);

  let x = MARGIN + 2;
  headers.forEach((h, i) => {
    doc.text(h, x, y);
    x += colWidths[i];
  });
  y += rowH;

  doc.setFont('helvetica', 'normal');
  doc.setTextColor(...THEME.body);
  doc.setFontSize(9);

  for (const row of rows) {
    if (y > PAGE_H - 24) {
      doc.addPage();
      y = MARGIN + 10;
    }
    let cx = MARGIN + 2;
    row.forEach((cell, i) => {
      const clipped = doc.splitTextToSize(cell, colWidths[i] - 4);
      doc.text(clipped, cx, y);
      cx += colWidths[i];
    });
    y += rowH;
    doc.setDrawColor(35, 48, 64);
    doc.setLineWidth(0.2);
    doc.line(MARGIN, y - 3, PAGE_W - MARGIN, y - 3);
  }

  return y + 6;
}

function drawSimplePieChart(
  doc: jsPDF,
  x: number,
  y: number,
  applications: { name: string; packets: number }[]
) {
  const colors: [number, number, number][] = [
    [34, 211, 238],
    [57, 255, 157],
    [255, 176, 32],
    [255, 59, 92],
    [129, 140, 248],
    [244, 114, 182],
  ];
  const total = applications.reduce((s, a) => s + a.packets, 0) || 1;
  let angle = -Math.PI / 2;
  const cx = x + 30;
  const cy = y + 30;
  const r = 24;

  applications.slice(0, 6).forEach((app, i) => {
    const slice = (app.packets / total) * Math.PI * 2;
    doc.setFillColor(...colors[i % colors.length]);
    const steps = 24;
    for (let s = 0; s < steps; s++) {
      const a1 = angle + (slice * s) / steps;
      const a2 = angle + (slice * (s + 1)) / steps;
      doc.triangle(
        cx,
        cy,
        cx + Math.cos(a1) * r,
        cy + Math.sin(a1) * r,
        cx + Math.cos(a2) * r,
        cy + Math.sin(a2) * r,
        'F'
      );
    }
    angle += slice;
  });

  doc.setFontSize(8);
  doc.setTextColor(...THEME.body);
  let ly = y;
  applications.slice(0, 6).forEach((app, i) => {
    doc.setFillColor(...colors[i % colors.length]);
    doc.rect(x + 68, ly, 4, 4, 'F');
    doc.text(`${app.name} (${app.packets})`, x + 76, ly + 3);
    ly += 6;
  });
}

function drawSimpleBarChart(
  doc: jsPDF,
  x: number,
  y: number,
  applications: { name: string; packets: number }[]
) {
  const data = applications.slice(0, 6);
  const max = Math.max(...data.map((d) => d.packets), 1);
  const barW = 14;
  const gap = 6;
  const chartH = 50;

  data.forEach((app, i) => {
    const h = (app.packets / max) * chartH;
    const bx = x + i * (barW + gap);
    doc.setFillColor(34, 211, 238);
    doc.rect(bx, y + chartH - h, barW, h, 'F');
    doc.setFontSize(7);
    doc.setTextColor(...THEME.body);
    const label = doc.splitTextToSize(app.name, barW + 4);
    doc.text(label, bx + barW / 2, y + chartH + 5, { align: 'center' });
  });
}

async function captureChart(elementId: string): Promise<string | null> {
  const el = document.getElementById(elementId);
  if (!el) return null;
  try {
    const canvas = await html2canvas(el, {
      backgroundColor: '#0f151c',
      scale: 2,
      logging: false,
    });
    return canvas.toDataURL('image/png');
  } catch {
    return null;
  }
}

export async function generatePdfReport(
  data: AnalyzeResponse,
  chartIds?: { pie?: string; bar?: string }
): Promise<void> {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const stats = data.statistics;
  const domains = stats.domains ?? [];
  const totalBytes = stats.totalBytes ?? 0;
  const generatedAt = new Date().toLocaleString();

  // Header band
  doc.setFillColor(...THEME.dark);
  doc.rect(0, 0, PAGE_W, 42, 'F');
  doc.setFillColor(...THEME.primary);
  doc.rect(0, 42, PAGE_W, 1.5, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(...THEME.headerText);
  doc.text('Deep Packet Inspection Report', MARGIN, 18);

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(9);
  doc.setTextColor(...THEME.headerSub);
  doc.text(`Generated: ${generatedAt}`, MARGIN, 28);
  doc.text(`Input File: ${data.originalName}`, MARGIN, 34);

  let y = 54;

  y = addSectionTitle(doc, 'Executive Summary', y);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...THEME.body);

  const summary = [
    ['Total Packets', stats.totalPackets.toLocaleString()],
    ['Total Bytes', formatBytes(totalBytes)],
    ['TCP Packets', stats.tcpPackets.toLocaleString()],
    ['UDP Packets', stats.udpPackets.toLocaleString()],
    ['Forwarded', stats.forwarded.toLocaleString()],
    ['Dropped', stats.dropped.toLocaleString()],
  ];

  summary.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...THEME.label);
    doc.text(label, MARGIN, y);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(...THEME.body);
    doc.text(value, MARGIN + 55, y);
    y += 7;
  });

  y += 4;
  y = addSectionTitle(doc, 'Blocking Rules Applied', y);
  doc.setFontSize(10);
  doc.setTextColor(...THEME.body);
  doc.text(`Blocked Applications: ${formatList(data.appliedRules.apps)}`, MARGIN, y);
  y += 6;
  doc.text(`Blocked Domains: ${formatList(data.appliedRules.domains)}`, MARGIN, y);
  y += 6;
  doc.text(`Blocked IPs: ${formatList(data.appliedRules.ips)}`, MARGIN, y);
  y += 10;

  y = addSectionTitle(doc, 'Application Breakdown', y);
  const appRows = stats.applications.map((a) => [
    a.name,
    a.packets.toLocaleString(),
    `${a.percentage.toFixed(1)}%`,
  ]);
  y = drawTable(
    doc,
    y,
    ['Application', 'Packets', 'Percentage'],
    appRows.length ? appRows : [['—', '0', '0%']],
    [70, 40, 40]
  );

  if (y > PAGE_H - 60) {
    doc.addPage();
    y = MARGIN + 10;
  }

  y = addSectionTitle(doc, 'Thread Utilization', y);
  const threadRows = stats.threads.map((t) => [
    `Thread ${t.thread}`,
    t.packets.toLocaleString(),
  ]);
  y = drawTable(
    doc,
    y,
    ['Thread', 'Packets Processed'],
    threadRows.length ? threadRows : [['—', '0']],
    [80, 60]
  );

  if (y > PAGE_H - 60) {
    doc.addPage();
    y = MARGIN + 10;
  }

  y = addSectionTitle(doc, 'Detected Domains', y);
  const domainRows = domains.map((d) => [domainName(d), domainApp(d)]);
  y = drawTable(
    doc,
    y,
    ['Domain', 'Detected Application'],
    domainRows.length ? domainRows : [['—', '—']],
    [90, 60]
  );

  doc.addPage();
  y = MARGIN + 10;
  y = addSectionTitle(doc, 'Charts', y);

  const pieImg = chartIds?.pie ? await captureChart(chartIds.pie) : null;
  const barImg = chartIds?.bar ? await captureChart(chartIds.bar) : null;

  if (pieImg) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...THEME.label);
    doc.text('Application Distribution', MARGIN, y);
    y += 4;
    doc.addImage(pieImg, 'PNG', MARGIN, y, 85, 60);
    y += 68;
  } else if (stats.applications.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...THEME.label);
    doc.text('Application Distribution', MARGIN, y);
    drawSimplePieChart(doc, MARGIN, y + 2, stats.applications);
    y += 70;
  }

  if (barImg) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...THEME.label);
    doc.text('Packets by Application', MARGIN, y);
    y += 4;
    doc.addImage(barImg, 'PNG', MARGIN, y, CONTENT_W, 55);
  } else if (stats.applications.length > 0) {
    doc.setFontSize(10);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(...THEME.label);
    doc.text('Packets by Application', MARGIN, y);
    drawSimpleBarChart(doc, MARGIN, y + 6, stats.applications);
  }

  const totalPages = doc.getNumberOfPages();
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p);
    addFooter(doc, p, totalPages);
  }

  const safeName = data.originalName.replace(/\.[^.]+$/, '').replace(/[^\w.-]+/g, '_');
  doc.save(`DPI_Report_${safeName}.pdf`);
}
